server:
  port: 8080

spring:
  datasource:
    name: car_rent_datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_rent_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCp
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
